### ISSUE TITLE
Default nonbreaking log driver.

### ISSUE THREAD

**Issue by kris914g** [cachewerk/bref-laravel-bridge#14]
Yesterday I had the pleasure of using this Laravel bridge for the first time, and the overall experience was very good. I only had a minor issue with the initial setup I got some chmod errors. The issue was regarding the logging which used the default Laravel settings. So I was curious if it could make sense to override the default logging setting to something more compatible with AWS such as stderr. I think this is something that is also done in the Briefs Laravel bridge, or maybe change the default path to /tmp instead of Laravel's default logging path. If you believe it is a good idea, I would like to make a PR.

Bref is doing something similar https://github.com/brefphp/laravel-bridge/blob/master/src/BrefServiceProvider.php#L58

**Comment by tillkruss** [comment]
Yes! Please open a PR 🙌

**Comment by georgeboot** [comment]
I believe we already overwrite the log driver to become `stderr` when it's the default `stack`.

https://github.com/cachewerk/bref-laravel-bridge/blob/184ae167113dcef1a143f9f184f734876e30ab72/src/BrefServiceProvider.php#L140

What version have you tested?

**Comment by kris914g** [comment]
According to my composer, I use the following `"cachewerk/bref-laravel-bridge": "^0.2.0",` I also tried to uncomment my own LOG_CHANNEL variable and it seems it works as intended. The issue seems to be about something else. And after your line reference, I agree that it looks fine.
