### ISSUE TITLE
Queues should use `failed_jobs`

### ISSUE THREAD

**Issue by tillkruss** [cachewerk/bref-laravel-bridge#30]

**Comment by georgeboot** [comment]
https://github.com/laravel/framework/blob/c6678dcc29cef263e4021018f3174cfdc12c5c5f/src/Illuminate/Queue/Console/WorkCommand.php#L194

Should be simple enough to add

**Comment by tillkruss** [comment]
- Is `JobReleasedAfterException` relevant to us?
- Why use `JobFailed` vs `JobExceptionOccurred`?

**Comment by georgeboot** [comment]
When the worker handles and exception, the `JobExceptionOccured` event is dispatched: https://github.com/laravel/framework/blob/c6678dcc29cef263e4021018f3174cfdc12c5c5f/src/Illuminate/Queue/Worker.php#L642

When that results in a job failure, the `JobFailed` event is dispatched: https://github.com/laravel/framework/blob/c6678dcc29cef263e4021018f3174cfdc12c5c5f/src/Illuminate/Queue/Jobs/Job.php#L194
