### ISSUE TITLE
Consider using KMS for secrets

### ISSUE THREAD

**Issue by tillkruss** [cachewerk/bref-laravel-bridge#8]
Encrypting secrets in a during artifact building and loading them from a file might be a better approach for scale. Requires PHP 8.1. Hat tip @GrahamCampbell.

https://github.com/GrahamCampbell/Envelope-Encryption

**Comment by tillkruss** [comment]
Use their new extension:

- https://aws.amazon.com/fr/about-aws/whats-new/2022/10/aws-parameters-secrets-lambda-extension/
- https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-integration-lambda-extensions.html

**Comment by GrahamCampbell** [comment]
Unfortunately the new extension still has really brutal rate limits that are hard limits. Unusable for anyone who has spikey workloads (spiky as in 0 req/s then suddenly 10k req/s). Those use cases will obliterate the rate limits.

**Comment by GrahamCampbell** [comment]
That is probably the 0.1% of people, though. The default api gateway and lambda quotas don't support that kind of bursting. 🤷

**Comment by tillkruss** [comment]
@GrahamCampbell: I appreciate the heads up! I'm gonna give this a try.

**Comment by tillkruss** [comment]
Or use something like this: https://blog.laravel.com/laravel-new-environment-encryption-commands

**Comment by georgeboot** [comment]
Currently, you can inject secret names that will be resolved from SSM to actual values during runtime.

I'd propose to add a check in there to see if the lambda extension is present, and if so, do the same thing but then load from the extension instead.

Alongside that, we could perhaps by default use SSM, but give an configuration option (env key?) to use secrets manager instead.

People with more complicated needs can cook up their own solution.

How does that sound?

I'd be happy to create a PR for this.

**Comment by tillkruss** [comment]
I'd love that. Can you include some instructions so we can add this to the readme?

**Comment by tillkruss** [comment]
@georgeboot: What do we want to do with this? Close it?
